### ISSUE TITLE
Basic test does not work (`process.env.WIN_DIR` undefined)

### ISSUE THREAD

**Issue by niftylettuce** [vutran/os-fonts#4]
You cannot use `path` with an undefined variable.

```bash
λ ~/Public/project/ master* node -i
> require('os-fonts');
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at Object.<anonymous> (/Users/user/Public/project/node_modules/os-fonts/index.js:15:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

**Comment by niftylettuce** [comment]
This is on OS X, but I'm sure this happens on Linux too and possibly even Windows itself.

**Comment by vutran** [comment]
`WINDIR` is a Windows-only environmental variable so running the test in Mac or Linux would cause this error.

The fix should have been fixed [here](https://github.com/vutran/os-fonts/blob/1f05bf60c65d74182e7bf053ea01e90837138f8c/index.js#L5).

**Comment by niftylettuce** [comment]
It wasn't the test, it was actually using it broke on Mac/Linux - so the package was broken, but thank you for fixing.

**Comment by niftylettuce** [comment]
Thanks for fixing this and publishing to NPM so quickly.

**Comment by vutran** [comment]
Np, let me know if you continue to have issues using this module.
